[advisories]
db-urls = ["https://github.com/rustsec/advisory-db"]
notice = "warn"
unmaintained = "warn"
vulnerability = "deny"
yanked = "deny"

[bans]
multiple-versions = "warn"
wildcards = "allow"

[licenses]
allow = [
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "MIT",
  "Unicode-DFS-2016",
]
copyleft = "warn"
deny = []

[sources]
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
unknown-git = "warn"
unknown-registry = "warn"
