---
name: Rust macOS CI

# yamllint disable-line rule:truthy
on:
  # yamllint disable-line rule:empty-values
  workflow_dispatch:

  # yamllint disable-line rule:empty-values
  pull_request:

  push:
    branches:
      - main
    tags-ignore:
      - "**"

permissions: read-all

jobs:
  build-and-test:
    name: "Build & test (Apple Silicon)"
    runs-on: macos-14
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
        with:
          xcode-version: latest-stable
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
      - run: brew install ffmpeg
      - run: cargo fmt --check
      - run: cargo clippy --all-targets -- -D warnings
      - run: cargo test
